apiVersion: v1
kind: Pod
metadata:
  name: pre-stop-hook-httpget
spec:
  containers:
  - image: luksa/kubia
    name: kubia
    lifecycle:
      preStop:
        httpGet:
          port: 8080
          path: shutdown
