#!/bin/bash

# async-parent : Asynchronous execution demo (parent)

echo "Parent: starting..."
echo "Parent: launching child script..."
./async-child_script &
pid=$!
echo "Parent: child (PID= $pid) launched."

echo "parent: continuing..."
sleep 2

echo "Parent: pausing to wait for child to finish..."
wait $pid

echo "Parent: child is finished. Continuing..."
echo "Parent: Parent is done. EXiting."
