#!/bin/bash

# file_info: simple file information program

file_info() {
	# file_info: function to display file information

	if [[ -e $1 ]]; then
		echo -e "\nFile Type:"
		file $1
		echo -e "\nFile Status:"
		stat $1
	else
		echo "$FUNCNAME: usage: $FUNCNAME file" >&2
		return 1
	fi
}

# call the func
file_info "$@"
file_info "$@"

# PROGNAME only show the file, not show her parent
PROGNAME=$(basename $0)

if [[ -e $1 ]]; then
	echo -e "\nFile type:"
	file $1
	echo -e "\nFile Status:"
	stat $1
else
	echo "$PROGNAME: usage: $PROGNAME file" >&2
	exit 1
fi

