#!/bin/bash

# while-count: display a series of numbers

count=1

while [ $count -le 5 ]; do
	clear
	echo $count
	count=$((count + 1))
	sleep 1
done
echo "Finished the while-count"

# while-menu: a menu driven system information program

DELAY=3
while true; do
	clear
	cat <<- _EOF_
		please Select:

		1. Display System Information
		2. Dispaly Disk Space
		3. Display Home Space Utilization
		0. Quit

	_EOF_
	read -p "Enter selection [0-3] > "

	if [[ $REPLY =~ ^[0-3]$ ]]; then
		if [[ $REPLY == 1 ]]; then
			echo "Hostname: $HOSTNAME"
			uptime
			sleep $DELAY 
			continue
		fi
		if [[ $REPLY == 2 ]]; then
			df -h
			sleep $DELAY 
			continue
		fi
		if [[ $REPLY == 3 ]]; then
			if [[ $(id -u) -eq 0 ]]; then
				echo "Home Space Utilization (ALL Users)"
				du -sh /home/*
			else
				echo "Home space Utilization ($USER)"
				du -sh $HOME
			fi
			sleep $DELAY 
			continue
		fi
		if [[ $REPLY == 0 ]]; then
			break
		fi
	else
		echo "Invalid entry."
		sleep $DELAY 
	fi
done
echo "Program terminated."
